project_id = "tshgpcanrsfckluqsxfb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_manual_linking = false

[functions.send-contact-email]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false

[functions.send-daily-red]
verify_jwt = false

[functions.training-booking]
verify_jwt = false