// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tshgpcanrsfckluqsxfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzaGdwY2FucnNmY2tsdXFzeGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTUxNTAsImV4cCI6MjA2NzY5MTE1MH0.eVQhD1K9xps5XYDaDXcDXBJ22IL-rZXcMorYtc97FNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);